### ISSUE TITLE
[Bug] Run.py takes wrong class for submission according to submitter's name

### ISSUE THREAD

**Issue by rettelx** [lypnol/adventofcode-2017#28]
**Issue**
If someone's name is after "submission" alphabetically speaking (if name is "Xavier" for instance...) , his results are always "None" when we run run.py.

**My guess**
Run.py uses class `Submission` instead of class `NameSubmission` if "Name" is after "Submission" alphabetically speaking, therefore the result that gets returned is `None` as `Submission.run()` in the base class.

Probably something to do with lines 73-76 of run.py :
```
        classes = inspect.getmembers(submission_module, inspect.isclass)
        for _, cls_submission in classes:
            if issubclass(cls_submission, Submission):
                return cls_submission
```

**Comment by lypnol** [comment]
Thanks ! We should add a condition to check if `cls_submission` is exactly `Submission` then it should not be added
